name:                haskell-test-lib
version:             0.1.0.0
github:              "githubuser/haskell-test-lib"
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2018 Author name here"

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on Github at <https://github.com/githubuser/haskell-test-lib#readme>

dependencies:
- base >= 4.7 && < 5
- CBOR
- generics-sop
- binary
- bytestring

library:
  source-dirs:
  - lib
  - libtenkei-haskell/src
  ghc-options: ""

executables:
  haskell-test-lib-exe:
    main:                Main.hs
    source-dirs:
    - app
    - libtenkei-haskell/src
    dependencies: haskell-test-lib
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -ltest-library
    - -L../tenkei-build
