[package]
name = "tenkei-rust"
version = "0.0.1"
authors = ["Tobias Bucher <tobiasbucher5991@gmail.com>"]

[profile.dev]
panic = "abort"

[lib]
crate-type = ["cdylib"]

[dependencies]
structopt = "0.2.5"
serde_cbor = "0.8.2"
