name:                tenkei-haskell
version:             0.1.0.0
github:              "githubuser/tenkei-haskell"
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2018 Author name here"

extra-source-files:
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on Github at <https://github.com/githubuser/tenkei-haskell#readme>

dependencies:
- base >= 4.7 && < 5
- binary
- bytestring
- CBOR

library:
  source-dirs: src
  ghc-options:

tests:
  tenkei-haskell-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - tenkei-haskell
